[main]
# Sets the font family to Iosevka Term and the font size to 12
font=Iosevka Term Nerd Font:size=14

[cursor]
# Format: <text-color> <cursor-color>
color=121212 e0e0e0

[colors]
background=121212
foreground=e0e0e0

selection-foreground=e0e0e0
selection-background=323232

## Normal colors
regular0=222222  # black
regular1=b9a0a0  # red
regular2=a0b9a0  # green
regular3=b9b0a0  # yellow
regular4=a0a0b9  # blue
regular5=b0a0b9  # magenta
regular6=a0b0b0  # cyan
regular7=b2b2b2  # white

## Bright colors
bright0=323232   # bright black
bright1=b9a0a0   # bright red
bright2=a0b9a0   # bright green
bright3=b9b0a0   # bright yellow
bright4=a0a0b9   # bright blue
bright5=b0a0b9   # bright magenta
bright6=a0b0b0   # bright cyan
bright7=d0d0d0   # bright white
