set -g prefix ^B

# set -g default-terminal "tmux-256color"
set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB' # set-option -g status-style bg=default # can make it transparent

set -g mouse on
set -g set-clipboard on          # use system clipboard
setw -g mode-keys vi
unbind v
bind v copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

set-option -g status "on"
set -g status-interval 2
set -g status-position bottom      # macOS / darwin style

# plugin manager tell the direction for tmux to install and store plugin
# but i don't use any plugin for tmux yet
#set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/.tmux/plugins 
# by default tmux will just intsall to the ~/.tmux/plugins

# Enable focus events
set -g focus-events on
# Make index start from 1
set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# set -g @plugin 'tmux-plugins/tpm'
# this tells tmux to execute the plugins manager from the directory that contain the plugins
# run '~/.tmux/plugins/tpm/tpm'
